version: '3'

services:
  store-api:
    container_name: "store-api-container"
    image: store-api-image
    build: ./apps/api
    ports:
      - "5000:5000"
    environment:
      ASPNETCORE_URLS: "http://*:5000"
      ASPNETCORE_ENVIRONMENT: "Development"
    links:
      - store-database

  store-database:
    container_name: "store-database-container"
    image: store-database-image
    build: ./database
    environment:
      SA_PASSWORD: "MyVeryStronkPassword1!"
      ACCEPT_EULA: "Y"
